name: Pack Docker Image
on:
  workflow_dispatch:
    inputs:
      UID:
        description: "User ID"
        required: true
        type: number
      GID:
        description: "Group ID"
        required: true
        type: number
      TML_VERSION:
        description: "Template Version"
        required: true
        type: string

jobs:
  Build-Docker-Image:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Build image
        run: |
          docker buildx build -t snowind/tml:${{ github.event.inputs.TML_VERSION }} --build-arg UID=${{ github.event.inputs.UID }} --build-arg GID=${{ github.event.inputs.GID }} --build-arg TML_VERSION=${{ github.event.inputs.TML_VERSION }} .
          docker save -o tml-${{ github.event.inputs.TML_VERSION }}-uid${{ github.event.inputs.UID }}-gid${{ github.event.inputs.GID }}.tar snowind/tml:${{ github.event.inputs.TML_VERSION }}
      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          body: "this release was generated by @${{ github.actor}}"
          artifacts: "tml-${{ github.event.inputs.TML_VERSION }}-uid${{ github.event.inputs.UID }}-gid${{ github.event.inputs.GID }}.tar"
          generateReleaseNotes: true
